# Generated by Django 6.0.3 on 2026-03-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city_or_village',
            field=models.CharField(max_length=100, verbose_name='град/село'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, verbose_name='държава'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='имейл'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='телефонен номер'),
        ),
    ]
